#!/usr/bin/env python3
"""Generate ../data.js by inlining every processed JSON as a window global.

Run from anywhere:  py analysis/build_data_js.py
Inlining (rather than fetch) keeps the site working on file:// and GitHub Pages
alike. data.js is generated — never hand-edit it; edit the JSON in
data/processed/ and re-run this.
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROC = ROOT / "data" / "processed"

# processed filename -> window global name
MAP = {
    "phase1_data.json":     "PHASE1",        # funnel, routes, durations, onshore-by-nation
    "phase1b_data.json":    "PHASE1B",       # decision speed, pending bands
    "phase2_data.json":     "PHASE2",        # council-party outcomes + Westminster alignment
    "phase2c_data.json":    "PHASE2C",       # count vs capacity weighting, 50MW bunching
    "phase2_refresh.json":  "PHASE2_REFRESH",# refreshed party data + capacity ladder + cap-wtd approval
    "phase2b_data.json":    "PHASE2B",        # MP / constituency level
    "phase3_land.json":     "PHASE3_LAND",    # capacity approved per km2 of land controlled, by party
    "phase3b_land.json":    "PHASE3B_LAND",   # land-based, 2015-2026 window, per year
    "phase4_party.json":    "PHASE4_PARTY",   # outcomes by party in control AT THE DECISION YEAR (+ time-to-decide)
}

lines = ["// Compiled REPD + council-control analysis. GENERATED by analysis/build_data_js.py — do not hand-edit."]
for fname, glob in MAP.items():
    p = PROC / fname
    if not p.exists():
        print(f"  skip (missing): {fname}")
        continue
    data = json.loads(p.read_text(encoding="utf-8"))
    lines.append(f"window.{glob} = {json.dumps(data, separators=(',', ':'))};")
    print(f"  {fname:24s} -> window.{glob}")

out = ROOT / "data.js"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"\nWrote {out} ({out.stat().st_size:,} bytes)")
